spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/fortest?tinyInt1isBit=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.l3vi.testTransactional.mapper: DEBUG