server:
  port: 8081
  servlet:
    context-path: /async

spring:
  mvc:
    static-path-pattern: /upload/**
  resources:
    static-locations: classpath:default/
  redis:
    host: localhost
    port: 6379
#    database: 5
#    password: yunkc321#
  datasource:
    platform: mysql
    hikari:
      username: faqrobot
      password: N5AFzUgI3uDml4zk
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.1.69:3306/v5_test_cs?tinyInt1isBit=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8