spring:
  profiles:
    active: aliyun
  redis:
    timeout: 6000
    host: localhost
    port: 6379

---
spring:
  profiles: local
  rabbitmq:
    username: admin
    password: admin
#    addresses: 192.168.2.50:5672,192.168.2.33:5672
    virtual-host: /
    host: localhost
    port: 5672
    #开启发送确认
    publisher-confirms: true
#    #开启发送失败退回
#    publisher-returns: true
    listener:
#      direct:
#        acknowledge-mode: manual
#        在每个消费者端能达到的最大的未确认的消息 设置为1：每次拉取一条
#        prefetch: 1
      simple:
        acknowledge-mode: manual
        prefetch: 1
        retry:
          #消费者因为业务异常未能正确处理消息，默认会一直重试，这里关闭重试机制
          enabled: false

---
spring:
  profiles: aliyun
  rabbitmq:
    username: guest
    password: guest
    #    addresses: 192.168.2.50:5672,192.168.2.33:5672
    virtual-host: /
    host: 47.111.83.154
    port: 5672
    #开启发送确认
    publisher-confirms: true
    #    #开启发送失败退回
    #    publisher-returns: true
    listener:
      #      direct:
      #        acknowledge-mode: manual
      #        在每个消费者端能达到的最大的未确认的消息 设置为1：每次拉取一条
      #        prefetch: 1
      simple:
        acknowledge-mode: manual
        prefetch: 1
        retry:
          #消费者因为业务异常未能正确处理消息，默认会一直重试，这里关闭重试机制
          enabled: false