spring:
  rabbitmq:
    username: admin
    password: admin
#    addresses: 192.168.2.50:5672,192.168.2.33:5672
    virtual-host: /
    host: localhost
    port: 5672
    #开启发送确认
    publisher-confirms: true
#    #开启发送失败退回
#    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual