spring:
  datasource:
    driver-class-name: com.sybase.jdbc4.jdbc.SybDriver
    url: jdbc:sybase:Tds:139.198.15.74:33069/om_test?charset=cp936
    username: sa
    password: password

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:log4j2.xml