server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://111.229.127.81:3306/bank1?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 996kid

feign:
  hystrix:
    enabled: true